# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_slim.py

from PyInstaller.utils.hooks import collect_data_files
import os

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[
        ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/Qt6Core.dll', 'PySide6'),
            ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/Qt6Gui.dll', 'PySide6'),
            ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/Qt6Widgets.dll', 'PySide6'),
            ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/Qt6Network.dll', 'PySide6'),
            ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/Qt6Svg.dll', 'PySide6'),
            ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/QtCore.pyd', 'PySide6'),
            ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/QtGui.pyd', 'PySide6'),
            ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/QtWidgets.pyd', 'PySide6'),
            ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/plugins/platforms/qwindows.dll', 'PySide6/Qt/plugins/platforms'),
            ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/plugins/imageformats/qjpeg.dll', 'PySide6/Qt/plugins/imageformats'),
            ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/plugins/imageformats/qico.dll', 'PySide6/Qt/plugins/imageformats'),
            ('C:/Users/Administrator/AppData/Local/Programs/Python/Python313/Lib/site-packages/PySide6/plugins/imageformats/qsvg.dll', 'PySide6/Qt/plugins/imageformats')
    ],
    datas=[],
    hiddenimports=[
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'asyncio',
        'asyncio.runners',
        'json',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PySide6.Qt3DAnimation',
            'PySide6.Qt3DCore',
            'PySide6.Qt3DExtras',
            'PySide6.Qt3DInput',
            'PySide6.Qt3DLogic',
            'PySide6.Qt3DRender',
            'PySide6.QtAsyncio',
            'PySide6.QtAxContainer',
            'PySide6.QtBluetooth',
            'PySide6.QtCharts',
            'PySide6.QtConcurrent',
            'PySide6.QtDataVisualization',
            'PySide6.QtDBus',
            'PySide6.QtDesigner',
            'PySide6.QtGraphs',
            'PySide6.QtHelp',
            'PySide6.QtHttpServer',
            'PySide6.QtLocation',
            'PySide6.QtMultimedia',
            'PySide6.QtMultimediaWidgets',
            'PySide6.QtNfc',
            'PySide6.QtOpenGL',
            'PySide6.QtOpenGLWidgets',
            'PySide6.QtPdf',
            'PySide6.QtPdfWidgets',
            'PySide6.QtPositioning',
            'PySide6.QtPrintSupport',
            'PySide6.QtQml',
            'PySide6.QtQuick',
            'PySide6.QtQuick3D',
            'PySide6.QtQuickWidgets',
            'PySide6.QtRemoteObjects',
            'PySide6.QtScxml',
            'PySide6.QtSensors',
            'PySide6.QtSerialBus',
            'PySide6.QtSerialPort',
            'PySide6.QtSql',
            'PySide6.QtStateMachine',
            'PySide6.QtSvg',
            'PySide6.QtSvgWidgets',
            'PySide6.QtTest',
            'PySide6.QtTextToSpeech',
            'PySide6.QtWebChannel',
            'PySide6.QtWebEngineCore',
            'PySide6.QtWebEngineQuick',
            'PySide6.QtWebEngineWidgets',
            'PySide6.QtWebSockets',
            'PySide6.QtXml',
        'Qt6WebEngineCore.dll',
            'Qt6WebEngineWidgets.dll',
            'opengl32sw.dll',
            'avcodec-61.dll',
            'avformat-61.dll',
            'avutil-58.dll',
            'Qt6Quick.dll',
            'Qt6QuickWidgets.dll',
            'Qt6Qml.dll',
            'Qt6QmlCompiler.dll',
            'Qt6Designer.dll',
            'Qt6DesignerComponents.dll',
            'Qt6Pdf.dll',
            'Qt6PdfWidgets.dll',
            'Qt63DCore.dll',
            'Qt63DRender.dll',
            'Qt63DExtras.dll',
            'Qt63DInput.dll',
            'Qt63DLogic.dll',
            'Qt63DAnimation.dll',
            'Qt6Charts.dll',
            'Qt6Graphs.dll',
            'Qt6DataVisualization.dll',
            'Qt6Multimedia.dll',
            'Qt6MultimediaWidgets.dll',
            'Qt6ShaderTools.dll',
            'Qt6Quick3D.dll',
            'Qt6Quick3DRuntimeRender.dll',
            'Qt6Quick3DUtils.dll',
            'Qt6QuickControls2.dll',
            'Qt6QuickControls2Impl.dll',
            'Qt6QuickDialogs2.dll',
            'Qt6QuickDialogs2QuickImpl.dll',
            'Qt6QuickLayouts.dll',
            'Qt6QuickTemplates2.dll',
            'Qt6Bluetooth.dll',
            'Qt6Location.dll',
            'Qt6Positioning.dll',
            'Qt6Nfc.dll',
            'Qt6Sensors.dll',
            'Qt6SerialPort.dll',
            'Qt6TextToSpeech.dll',
            'Qt6RemoteObjects.dll',
            'Qt6Scxml.dll',
            'Qt6StateMachine.dll',
            'Qt6Test.dll',
            'Qt6HttpServer.dll',
            'Qt6WebSockets.dll',
            'Qt6WebChannel.dll',
            'Qt6OpenGL.dll',
            'Qt6OpenGLWidgets.dll',
            'Qt6VirtualKeyboard.dll',
        'matplotlib', 'numpy', 'scipy', 'pandas',
        'PIL', 'cv2', 'sklearn', 'tensorflow', 'torch',
        'tkinter', 'wx',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# ── 过滤掉大文件 DLL（即使被依赖分析拉进来也踢出去）──────────
EXCLUDE_DLL_NAMES = {name.lower() for name in ['Qt6WebEngineCore.dll', 'Qt6WebEngineWidgets.dll', 'opengl32sw.dll', 'avcodec-61.dll', 'avformat-61.dll', 'avutil-58.dll', 'Qt6Quick.dll', 'Qt6QuickWidgets.dll', 'Qt6Qml.dll', 'Qt6QmlCompiler.dll', 'Qt6Designer.dll', 'Qt6DesignerComponents.dll', 'Qt6Pdf.dll', 'Qt6PdfWidgets.dll', 'Qt63DCore.dll', 'Qt63DRender.dll', 'Qt63DExtras.dll', 'Qt63DInput.dll', 'Qt63DLogic.dll', 'Qt63DAnimation.dll', 'Qt6Charts.dll', 'Qt6Graphs.dll', 'Qt6DataVisualization.dll', 'Qt6Multimedia.dll', 'Qt6MultimediaWidgets.dll', 'Qt6ShaderTools.dll', 'Qt6Quick3D.dll', 'Qt6Quick3DRuntimeRender.dll', 'Qt6Quick3DUtils.dll', 'Qt6QuickControls2.dll', 'Qt6QuickControls2Impl.dll', 'Qt6QuickDialogs2.dll', 'Qt6QuickDialogs2QuickImpl.dll', 'Qt6QuickLayouts.dll', 'Qt6QuickTemplates2.dll', 'Qt6Bluetooth.dll', 'Qt6Location.dll', 'Qt6Positioning.dll', 'Qt6Nfc.dll', 'Qt6Sensors.dll', 'Qt6SerialPort.dll', 'Qt6TextToSpeech.dll', 'Qt6RemoteObjects.dll', 'Qt6Scxml.dll', 'Qt6StateMachine.dll', 'Qt6Test.dll', 'Qt6HttpServer.dll', 'Qt6WebSockets.dll', 'Qt6WebChannel.dll', 'Qt6OpenGL.dll', 'Qt6OpenGLWidgets.dll', 'Qt6VirtualKeyboard.dll']}

def filter_bins(toc):
    kept, removed = [], []
    for name, src, kind in toc:
        fname = os.path.basename(name).lower()
        if fname in EXCLUDE_DLL_NAMES:
            removed.append(fname)
        else:
            kept.append((name, src, kind))
    if removed:
        print(f"  [slim] 排除 {len(removed)} 个大文件: {removed[:5]}...")
    return kept

a.binaries = filter_bins(a.binaries)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='UAMProxy_v1.100',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,           # 使用 UPX 压缩（若已安装可进一步减小体积约 20%）
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,      # 隐藏控制台
    
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
